name: build

on:
  push:
    branches: '*'
  pull_request:
    branches: 'master'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up jdk 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        
    - name: Run tests
      run: mvn --batch-mode --update-snapshots test
      
    - name: Build
      run: mvn --batch-mode --update-snapshots -DskipTests=true verify
     
    - name: Create artefact
      run: mkdir staging && cp target/*.jar staging
      
    - name: Upload a build artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: staging
        retention-days: 7
      
  send:
      needs: build
      
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/download-artifact@v3
        with:
          name: package
          
#       - name: Archive files
#         run: |
#           sudo apt-get update
#           sudo apt-get install zip
#           zip -r "package.zip" * 
          
      - name: Upload to google drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "staging/*.jar"
          folderId: ${{ secrets.folderId }}
          name: "/${{ github.run_id }}/package_${{ github.run_number }}.zip"
          overwrite: "true" 
    
