name: build

on:
  push:
    branches: '*'
  pull_request:
    branches: 'master'
  workflow_dispatch:

jobs:
  build_and_upload:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        
    - name: Run
      run: |
       mvn --batch-mode --update-snapshots verify
       mkdir staging && cp target/*.jar staging
      
    - name: Upload a build artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: staging
        
    - name: Archive files
      run: |
        sudo apt-get update
        sudo apt-get install zip
        zip -r "package.zip" * 
          
    - name: Upload to google drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.credentials }}
        filename: "package.zip"
        folderId: ${{ secrets.folderId }}
        name: "/$GITHUB_RUN_ID/package_$(date +%s).zip"
        overwrite: "true" 
    
