name: pipline

on:
  push:
    branches: '*'
  pull_request:
    branches: 'master'
  workflow_dispatch:

jobs:

  lint:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Lint
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  tests:
  
    runs-on: ubuntu-latest
    
    needs: lint
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Set up jdk 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
        
      - name: Run tests
        run: mvn --batch-mode --update-snapshots test
 
  build:

    runs-on: ubuntu-latest
    
    needs: tests
    
    steps:
    
    - name: Send text message to telegram 
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
    - uses: actions/checkout@v3
      
    - name: Set up jdk 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
      
    - name: Build
      run: mvn --batch-mode --update-snapshots -DskipTests=true verify
     
    - name: Create artefact
      run: mkdir staging && cp target/*.jar staging
      
    - name: Upload a build artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: staging
        retention-days: 7
      
  upload:
  
      needs: build
      
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/download-artifact@v3
        with:
          name: package
      
      - name: Upload to google drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: devops-1.0-SNAPSHOT.jar
          folderId: ${{ secrets.folderId }}
          name: "/${{ github.run_id }}/package_${{ github.run_number }}.jar"
          overwrite: "true" 
          
      - name: Send file to telegram 
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: devops-1.0-SNAPSHOT.jar
          message: file -> 
       
            
  docker:
  
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
          

        
  deploy:
  
    runs-on: self-hosted
    
    needs: docker 
    
    steps:
      - run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
      - run: docker run ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
      
    
